# Версия docker-compose
version: '3.7'
# Список наших сервисов (контейнеров)
services:
    nginx:
 # используем последний стабильный образ nginx
        image: nginx:latest
     
        # Назовем свой контейнер по красивому
        container_name: nginx

        # маршрутизируем порты 
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www

    phpmyadmin:

        image: phpmyadmin/phpmyadmin
        
        container_name: phpmyadmin
        
        ports:
            - 8090:80
        
        links:
            - mysql:db  

    mysql:

        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            # прописываем название нашего MySQL хоста
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
